services:
  pbx-db:
    container_name: pbx-db
    hostname: pbx-db
    image: postgres:16-bullseye
    environment:
      POSTGRES_DB: fusionpbx
      POSTGRES_USER: fusionpbx
    volumes:
      - ../data-pbx-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped